### ISSUE TITLE
Public Contact Form Wording Issue

### ISSUE THREAD

**Issue by RobertMcCririck** [jackspyder/Podiatry#14]
Could this be changed to match the suggested changes from the top paragraph for online booking? And could the title be changed for 'booking' to 'Contact Form'?

https://github.com/jackspyder/Podiatry/issues/2

**Comment by jackspyder** [comment]
References https://github.com/jackspyder/Podiatry/issues/2

**Comment by jackspyder** [comment]
https://github.com/jackspyder/Podiatry/issues/2
