### ISSUE TITLE
'Conditions' Page

### ISSUE THREAD

**Issue by RobertMcCririck** [jackspyder/Podiatry#4]
- Can the images be resized to remove the white banner below?
- Can the top line be changed to read "Browse through our list of common foot, ankle and lower limb conditions that may arise. Please note, this list is not exhaustive and should not be used to self-diagnose."

**Comment by jackspyder** [comment]
Altered issue to:
https://github.com/jackspyder/Podiatry/issues/5
https://github.com/jackspyder/Podiatry/issues/6
